spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecapi_develop
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.github.onozaty.mybatis.pg.type.list
cors:
  allowedOrigins: http://localhost:5173
logging:
  level:
    com:
      example:
        ecapi:
          security:
            user:
              UserRepository: DEBUG
