spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecapi_develop
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
aws:
  s3:
    buckets:
      products: ecapi-products
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.github.onozaty.mybatis.pg.type.list
cors:
  allowedOrigins: http://localhost:3000
logging:
  level:
    root: DEBUG